title: Ryan Goebel # your name (or website title) here
logo: "/images/ryan_goebel_head_shot.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>MPS in Analytics<br>Applied Machine Intelligence </b>
  <br>
  The Roux Institute <br>at Northeastern University
  <br><br>
  <a href="https://www.linkedin.com/in/ryangoebel/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
